[package]
name = "konsumer_offsets"
version = "0.1.0"
edition = "2021"
authors = ["Ivan De Marino <detronizator@gmail.com>"]
repository = "TODO"
homepage = "TODO"
description = "TODO"
license = "MIT OR Apache-2.0"
keywords = ["apache", "kafka", "parser", "__consumer_offsets"]
categories = ["encoding", "network-programming", "parsing"]
exclude = [
    ".gitignore",
    ".github/",
]

[dependencies]
bytes_parser = "0.1.2"
thiserror = "1.0.38"

[dev-dependencies]
rstest = "0.16.0"
